// ============================================================
// 人教版 PEP 四年级上册英语数据库
// 同时支持新版(2025)和旧版教材
// ============================================================

const PEP_DATA = {
  // 年级选择
  grades: [
    { id: 'grade4', name: '四年级上册' }
  ],

  // 版本选择
  versions: [
    { id: 'new', name: '2025新版', desc: 'Unit1 Helping at home ...' },
    { id: 'old', name: '经典版', desc: 'Unit1 My classroom ...' }
  ],

  // ===================== 2025新版教材 =====================
  new: [
    // ---------- Unit 1: Helping at home ----------
    {
      id: 'u1',
      title: 'Unit 1',
      subtitle: 'Helping at home',
      titleCN: '在家帮忙',
      icon: '🏠',
      words: [
        { en: 'PE', zh: '体育(课)', type: 'noun' },
        { en: 'job', zh: '工作;职业', type: 'noun' , phonetic: '/dʒɒb/' },
        { en: 'doctor', zh: '医生', type: 'noun' , phonetic: '/ˈdɒktə/' },
        { en: 'farmer', zh: '农民', type: 'noun' , phonetic: '/ˈfɑːmə/' },
        { en: 'nurse', zh: '护士', type: 'noun' , phonetic: '/nɜːs/' },
        { en: 'cook', zh: '厨师;烹饪', type: 'noun' , phonetic: '/kʊk/' },
        { en: 'driver', zh: '司机', type: 'noun' , phonetic: '/ˈdraɪvə/' },
        { en: 'firefighter', zh: '消防队员', type: 'noun' , phonetic: '/ˈfaɪəfaɪtə/' },
        { en: 'fire', zh: '火;火灾', type: 'noun' , phonetic: '/ˈfaɪə/' },
        { en: 'fight', zh: '战斗;斗争', type: 'verb' , phonetic: '/faɪt/' },
        { en: 'help', zh: '帮助', type: 'verb' , phonetic: '/help/' },
        { en: 'helpful', zh: '有帮助的', type: 'adj' , phonetic: '/ˈhelpfl/' },
        { en: 'clean', zh: '打扫;干净的', type: 'verb' , phonetic: '/kliːn/' },
        { en: 'floor', zh: '地板;地面', type: 'noun' , phonetic: '/flɔː/' },
        { en: 'sweep', zh: '打扫;扫', type: 'verb' , phonetic: '/swiːp/' },
        { en: 'factory', zh: '工厂', type: 'noun' , phonetic: '/ˈfæktəri/' },
        { en: 'worker', zh: '工人', type: 'noun' , phonetic: '/ˈwɜːkə/' },
        { en: 'office', zh: '办公室', type: 'noun' , phonetic: '/ˈɒfɪs/' },
        { en: 'together', zh: '一起', type: 'adv' , phonetic: '/təˈɡeðə/' },
        { en: 'fun', zh: '乐趣;有趣的', type: 'noun' , phonetic: '/fʌn/' },
      ],
      phrases: [
        { en: 'sweep the floor', zh: '扫地' },
        { en: 'cook together', zh: '一起做饭' },
        { en: 'have fun', zh: '玩得开心' },
        { en: 'PE teacher', zh: '体育老师' },
        { en: 'office worker', zh: '办公室职员' },
        { en: 'factory worker', zh: '工厂工人' },
        { en: 'do some chores', zh: '做家务' },
        { en: 'make friends', zh: '交朋友' },
      ],
      sentences: [
        { en: "What's your mother's job?", zh: "你妈妈做什么工作？" },
        { en: "She's a doctor.", zh: "她是医生。" },
        { en: "Mum and Dad are busy and tired.", zh: "爸爸妈妈又忙又累。" },
        { en: "What can we do for them?", zh: "我们能为他们做些什么？" },
        { en: "We can do some chores.", zh: "我们可以做一些家务活。" },
        { en: "Is this your father?", zh: "这是你的爸爸吗？" },
        { en: "Yes, it is.", zh: "是的。" },
        { en: "No, it isn't.", zh: "不，不是。" },
        { en: "What's your father's job?", zh: "你爸爸的工作是什么？" },
        { en: "He's a doctor.", zh: "他是一名医生。" },
        { en: "She's a nurse.", zh: "她是一名护士。" },
        { en: "I'm helpful at home.", zh: "我在家很能干。" },
        { en: "I can sweep the floor.", zh: "我会扫地。" },
        { en: "Let's cook together!", zh: "我们一起做饭吧！" },
        { en: "That's great!", zh: "太好了！" },
      ],
      grammar: [
        { title: 'Is this/that ...? 句型', content: '用来询问"这是/那是……吗？"回答用 Yes, it is. / No, it isn\'t.' },
        { title: 'What\'s ... job? 句型', content: '用来询问某人的职业。回答用 He\'s/She\'s a + 职业。' },
        { title: '人称代词 he/she', content: 'he 指男性"他"，she 指女性"她"。He\'s = He is, She\'s = She is。' },
      ],
      dialogues: [
        { speaker: 'Sarah', en: "Is this your mother?", zh: "这是你的妈妈吗？" },
        { speaker: 'Amy', en: "Yes, it is.", zh: "是的，她是。" },
        { speaker: 'Sarah', en: "What's your mother's job?", zh: "你妈妈做什么工作？" },
        { speaker: 'Amy', en: "She's a doctor.", zh: "她是医生。" },
        { speaker: 'Sarah', en: "Is this your father?", zh: "这是你的爸爸吗？" },
        { speaker: 'Amy', en: "Yes, it is. He's a doctor, too.", zh: "是的。他也是医生。" },
        { speaker: 'Amy', en: "Mum and Dad are busy and tired.", zh: "爸爸妈妈又忙又累。" },
        { speaker: 'Wu Binbin', en: "What can we do for them?", zh: "我们能为他们做些什么？" },
        { speaker: 'Amy', en: "We can do some chores.", zh: "我们可以做一些家务活。" },
        { speaker: 'Wu Binbin', en: "I can sweep the floor.", zh: "我会扫地。" },
        { speaker: 'Amy', en: "Let's cook together!", zh: "我们一起做饭吧！" },
        { speaker: 'Wu Binbin', en: "That's great!", zh: "太好了！" },
      ]
    },
    // ---------- Unit 2: My friends ----------
    {
      id: 'u2',
      title: 'Unit 2',
      subtitle: 'My friends',
      titleCN: '我的朋友',
      icon: '👫',
      words: [
        { en: 'friend', zh: '朋友', type: 'noun' , phonetic: '/frend/' },
        { en: 'friendly', zh: '友好的', type: 'adj' , phonetic: '/ˈfrendli/' },
        { en: 'quiet', zh: '安静的', type: 'adj' , phonetic: '/ˈkwaɪət/' },
        { en: 'strong', zh: '强壮的', type: 'adj' , phonetic: '/strɒŋ/' },
        { en: 'tall', zh: '高的', type: 'adj' , phonetic: '/tɔːl/' },
        { en: 'short', zh: '矮的;短的', type: 'adj' , phonetic: '/ʃɔːt/' },
        { en: 'thin', zh: '瘦的', type: 'adj' , phonetic: '/θɪn/' },
        { en: 'hair', zh: '头发', type: 'noun' , phonetic: '/heə/' },
        { en: 'long', zh: '长的', type: 'adj' , phonetic: '/lɒŋ/' },
        { en: 'shoe', zh: '鞋', type: 'noun' , phonetic: '/ʃuː/' },
        { en: 'glasses', zh: '眼镜', type: 'noun' , phonetic: '/ˈɡlɑːsɪz/' },
        { en: 'right', zh: '正确的;右边', type: 'adj' , phonetic: '/raɪt/' },
        { en: 'his', zh: '他的', type: 'pron' , phonetic: '/hɪz/' },
        { en: 'her', zh: '她的', type: 'pron' , phonetic: '/hɜː/' },
        { en: 'name', zh: '名字', type: 'noun' , phonetic: '/neɪm/' },
        { en: 'best', zh: '最好的', type: 'adj' , phonetic: '/best/' },
        { en: 'brown', zh: '棕色的', type: 'adj' , phonetic: '/braʊn/' },
        { en: 'blue', zh: '蓝色的', type: 'adj' , phonetic: '/bluː/' },
      ],
      phrases: [
        { en: 'long hair', zh: '长头发' },
        { en: 'short hair', zh: '短头发' },
        { en: 'brown shoes', zh: '棕色的鞋子' },
        { en: 'blue glasses', zh: '蓝色的眼镜' },
        { en: 'tall and strong', zh: '又高又壮' },
        { en: 'quiet and friendly', zh: '安静又友好' },
        { en: 'his name', zh: '他的名字' },
        { en: 'her friend', zh: '她的朋友' },
      ],
      sentences: [
        { en: "What's your friend's name?", zh: "你的朋友叫什么名字？" },
        { en: "His name is Zhang Peng.", zh: "他叫张鹏。" },
        { en: "He's tall and strong.", zh: "他又高又壮。" },
        { en: "He's also kind. He often helps me.", zh: "他也很友善。他经常帮助我。" },
        { en: "Who's your best friend?", zh: "谁是你最好的朋友？" },
        { en: "Chen Jie. She's funny. She often makes me smile.", zh: "陈杰。她很有趣。她经常让我开心。" },
        { en: "I have a new friend.", zh: "我有一个新朋友。" },
        { en: "What's his name?", zh: "他叫什么名字？" },
        { en: "He is tall and strong.", zh: "他又高又壮。" },
        { en: "She has long hair.", zh: "她有长头发。" },
        { en: "She has blue glasses.", zh: "她戴着蓝色眼镜。" },
        { en: "Who is he?", zh: "他是谁？" },
        { en: "He is my best friend.", zh: "他是我最好的朋友。" },
        { en: "He has brown shoes.", zh: "他穿着棕色的鞋子。" },
      ],
      grammar: [
        { title: 'He/She has ...', content: '描述某人拥有……。He has ... / She has ... 注意第三人称单数用 has。' },
        { title: '形容词描述外貌', content: 'tall(高的), short(矮的), strong(强壮的), thin(瘦的), quiet(安静的), friendly(友好的)' },
        { title: 'his vs her', content: 'his = 他的(男), her = 她的(女)。What\'s his/her name? = 他/她叫什么名字？' },
      ],
      dialogues: [
        { speaker: 'John', en: "I have a new friend.", zh: "我有一个新朋友。" },
        { speaker: 'Sarah', en: "What's his name?", zh: "他叫什么名字？" },
        { speaker: 'John', en: "His name is Zhang Peng.", zh: "他叫张鹏。" },
        { speaker: 'Sarah', en: "Is he tall?", zh: "他高吗？" },
        { speaker: 'John', en: "Yes, he is. He's tall and strong.", zh: "是的，他又高又壮。" },
        { speaker: 'Sarah', en: "Does he have glasses?", zh: "他戴眼镜吗？" },
        { speaker: 'John', en: "No. He has blue shoes.", zh: "不。他穿蓝色的鞋子。" },
        { speaker: 'Sarah', en: "Is he friendly?", zh: "他友好吗？" },
        { speaker: 'John', en: "Yes, he is very friendly.", zh: "是的，他很友好。" },
      ]
    },
    // ---------- Unit 3: Places we live in ----------
    {
      id: 'u3',
      title: 'Unit 3',
      subtitle: 'Places we live in',
      titleCN: '我们居住的地方',
      icon: '🏘️',
      words: [
        { en: 'place', zh: '地方', type: 'noun' , phonetic: '/pleɪs/' },
        { en: 'live', zh: '居住', type: 'verb' , phonetic: '/lɪv/' },
        { en: 'community', zh: '社区', type: 'noun' , phonetic: '/kəˈmjuːnəti/' },
        { en: 'house', zh: '房子', type: 'noun' , phonetic: '/haʊs/' },
        { en: 'street', zh: '街道', type: 'noun' , phonetic: '/striːt/' },
        { en: 'playground', zh: '操场;游乐场', type: 'noun' , phonetic: '/ˈpleɪɡraʊnd/' },
        { en: 'park', zh: '公园', type: 'noun' , phonetic: '/pɑːk/' },
        { en: 'gym', zh: '体育馆', type: 'noun' },
        { en: 'museum', zh: '博物馆', type: 'noun' },
        { en: 'library', zh: '图书馆', type: 'noun' },
        { en: 'shop', zh: '商店', type: 'noun' , phonetic: '/ʃɒp/' },
        { en: 'hospital', zh: '医院', type: 'noun' , phonetic: '/ˈhɒspɪtl/' },
        { en: 'pet hospital', zh: '宠物医院', type: 'noun' },
        { en: 'school', zh: '学校', type: 'noun' , phonetic: '/skuːl/' },
        { en: 'favourite', zh: '最喜欢的', type: 'adj' },
        { en: 'near', zh: '在……附近', type: 'prep' , phonetic: '/nɪə/' },
        { en: 'there is', zh: '有(单数)', type: 'phrase' },
        { en: 'there are', zh: '有(复数)', type: 'phrase' },
        { en: 'many', zh: '许多', type: 'adj' },
      ],
      phrases: [
        { en: 'live in a community', zh: '住在一个社区里' },
        { en: 'places we live in', zh: '我们居住的地方' },
        { en: 'play on the playground', zh: '在操场上玩' },
        { en: 'in the park', zh: '在公园里' },
        { en: 'go to the gym', zh: '去体育馆' },
        { en: 'visit the museum', zh: '参观博物馆' },
        { en: 'near my house', zh: '在我家附近' },
        { en: 'my favourite place', zh: '我最喜欢的地方' },
      ],
      sentences: [
        { en: "There is a playground. We often play there.", zh: "那里有个游乐场。我们经常在那里玩儿。" },
        { en: "There is a taijiquan club.", zh: "这里有一个太极拳俱乐部。" },
        { en: "There are many people.", zh: "这里有好多人。" },
        { en: "There is a gym too.", zh: "这里还有一个体育馆。" },
        { en: "Great! Let's do some sports.", zh: "太棒了！我们一起做运动吧。" },
        { en: "My favourite place is the museum.", zh: "我最喜欢的地方是博物馆。" },
        { en: "Where do you live?", zh: "你住在哪里？" },
        { en: "I live in a community.", zh: "我住在一个社区里。" },
        { en: "What's near your house?", zh: "你家附近有什么？" },
        { en: "There is a park near my house.", zh: "我家附近有一个公园。" },
      ],
      grammar: [
        { title: 'There is / There are', content: '表示"某地有某物"。There is + 单数，There are + 复数。There is a playground. There are many people.' },
        { title: 'Where do you live?', content: '询问对方住在哪里。回答 I live in + 地点。' },
        { title: '介词 near', content: 'near 表示"在……附近"。near my house = 在我家附近。' },
      ]
    },
    // ---------- Unit 4: Helping in the community ----------
    {
      id: 'u4',
      title: 'Unit 4',
      subtitle: 'Helping in the community',
      titleCN: '在社区帮忙',
      icon: '🤝',
      words: [
        { en: 'community', zh: '社区', type: 'noun' , phonetic: '/kəˈmjuːnəti/' },
        { en: 'neighbour', zh: '邻居', type: 'noun' },
        { en: 'firefighter', zh: '消防员', type: 'noun' , phonetic: '/ˈfaɪəfaɪtə/' },
        { en: 'driver', zh: '司机', type: 'noun' , phonetic: '/ˈdraɪvə/' },
        { en: 'bus driver', zh: '公交车司机', type: 'noun' },
        { en: 'help', zh: '帮助', type: 'verb' , phonetic: '/help/' },
        { en: 'people', zh: '人们', type: 'noun' , phonetic: '/ˈpiːpl/' },
        { en: 'important', zh: '重要的', type: 'adj' },
        { en: 'job', zh: '工作', type: 'noun' , phonetic: '/dʒɒb/' },
        { en: 'make the bed', zh: '铺床', type: 'phrase' },
        { en: 'bed', zh: '床', type: 'noun' , phonetic: '/bed/' },
        { en: 'often', zh: '经常', type: 'adv' },
        { en: 'take', zh: '带;送', type: 'verb' },
        { en: 'every day', zh: '每天', type: 'phrase' },
        { en: 'school bus', zh: '校车', type: 'noun' },
      ],
      phrases: [
        { en: 'help people', zh: '帮助人们' },
        { en: 'in the community', zh: '在社区里' },
        { en: 'school bus driver', zh: '校车司机' },
        { en: 'take us to school', zh: '送我们去学校' },
        { en: 'every day', zh: '每天' },
        { en: 'make the bed', zh: '铺床' },
        { en: 'an important job', zh: '一份重要的工作' },
        { en: 'helping in the community', zh: '在社区帮忙' },
      ],
      sentences: [
        { en: "Our neighbour is a firefighter. He often helps people.", zh: "我们的邻居是消防员。他经常帮助别人。" },
        { en: "He's a school bus driver. He takes us to school every day.", zh: "他是校车司机。他每天送我们去学校。" },
        { en: "That's an important job too!", zh: "那个工作也很重要！" },
        { en: "Chen Jie is making the bed.", zh: "陈杰正在铺床。" },
        { en: "What does your father do?", zh: "你爸爸是做什么的？" },
        { en: "He is a doctor.", zh: "他是一名医生。" },
        { en: "Where does he work?", zh: "他在哪里工作？" },
        { en: "He works at a hospital.", zh: "他在医院工作。" },
        { en: "My mother is a teacher.", zh: "我妈妈是一名老师。" },
        { en: "She works at a school.", zh: "她在学校工作。" },
      ],
      grammar: [
        { title: '现在进行时', content: 'be + 动词-ing 表示正在做。Chen Jie is making the bed. = 陈杰正在铺床。' },
        { title: 'often 的用法', content: 'often 表示"经常"，放在动词前面。He often helps people. = 他经常帮助别人。' },
        { title: 'What does ... do?', content: '用来询问某人的职业。What does your father do? = 你爸爸是做什么的？' },
      ]
    },
    // ---------- Unit 5: Weather and us ----------
    {
      id: 'u5',
      title: 'Unit 5',
      subtitle: 'Weather and us',
      titleCN: '天气和我们',
      icon: '🌤️',
      words: [
        { en: 'weather', zh: '天气', type: 'noun' , phonetic: '/ˈweðə/' },
        { en: 'sunny', zh: '晴朗的', type: 'adj' , phonetic: '/ˈsʌni/' },
        { en: 'rainy', zh: '下雨的', type: 'adj' , phonetic: '/ˈreɪni/' },
        { en: 'cloudy', zh: '多云的', type: 'adj' , phonetic: '/ˈklaʊdi/' },
        { en: 'windy', zh: '有风的', type: 'adj' , phonetic: '/ˈwɪndi/' },
        { en: 'snowy', zh: '下雪的', type: 'adj' , phonetic: '/ˈsnəʊi/' },
        { en: 'hot', zh: '热的', type: 'adj' , phonetic: '/hɒt/' },
        { en: 'cold', zh: '冷的', type: 'adj' , phonetic: '/kəʊld/' },
        { en: 'warm', zh: '温暖的', type: 'adj' , phonetic: '/wɔːm/' },
        { en: 'cool', zh: '凉爽的', type: 'adj' , phonetic: '/kuːl/' },
        { en: 'outside', zh: '在外面', type: 'adv' , phonetic: '/ˌaʊtˈsaɪd/' },
        { en: 'fly', zh: '飞;放(风筝)', type: 'verb' , phonetic: '/flaɪ/' },
        { en: 'kite', zh: '风筝', type: 'noun' , phonetic: '/kaɪt/' },
        { en: 'degree', zh: '度;度数', type: 'noun' },
        { en: 'world', zh: '世界', type: 'noun' },
        { en: 'report', zh: '报告', type: 'noun' },
        { en: 'put on', zh: '穿上', type: 'phrase' , phonetic: '/pʊt ɒn/' },
        { en: 'take off', zh: '脱下', type: 'phrase' },
      ],
      phrases: [
        { en: 'fly a kite', zh: '放风筝' },
        { en: 'put on your coat', zh: '穿上你的外套' },
        { en: 'take off your hat', zh: '脱下你的帽子' },
        { en: 'weather report', zh: '天气预报' },
        { en: 'go outside', zh: '出去' },
        { en: 'be careful', zh: '小心' },
        { en: 'how about', zh: '……怎么样' },
      ],
      sentences: [
        { en: "Hello! Mark speaking.", zh: "你好！我是马克。" },
        { en: "Hi, Mark! This is John. What's the weather like in Sydney?", zh: "嗨，马克！我是约翰。悉尼的天气怎么样？" },
        { en: "Well, it's sunny today.", zh: "噢，今天是晴天。" },
        { en: "It's only two degrees in Beijing.", zh: "北京只有两度。" },
        { en: "It's raining now.", zh: "现在下雨了。" },
        { en: "We can't play basketball in the park.", zh: "我们不能在公园打篮球了。" },
        { en: "It's OK. We can go to the library.", zh: "没关系。我们可以去图书馆。" },
        { en: "It's hot and sunny here.", zh: "这里很热，是个大晴天。" },
        { en: "Their children swim in the pool.", zh: "他们的孩子在泳池里游泳。" },
        { en: "What's the weather like today?", zh: "今天天气怎么样？" },
        { en: "It's sunny and warm.", zh: "晴朗又温暖。" },
        { en: "Is it cold outside?", zh: "外面冷吗？" },
        { en: "Yes, it is. Put on your coat.", zh: "是的，穿上你的外套。" },
        { en: "Can I go outside now?", zh: "我现在可以出去吗？" },
        { en: "It's rainy. Take your umbrella.", zh: "下雨了，带上你的雨伞。" },
      ],
      grammar: [
        { title: 'What\'s the weather like?', content: '询问天气。回答用 It\'s + 天气形容词(sunny, rainy, cold...) 。' },
        { title: '祈使句', content: 'Put on your coat.(穿上外套) / Be careful!(小心) 用动词原形开头，表达命令或建议。' },
        { title: 'Can I ...?', content: 'Can I go outside? = 我可以出去吗？用来请求许可。回答 Yes, you can. / No, you can\'t.' },
      ]
    },
    // ---------- Unit 6: Changing for the seasons ----------
    {
      id: 'u6',
      title: 'Unit 6',
      subtitle: 'Changing for the seasons',
      titleCN: '季节变化',
      icon: '🍂',
      words: [
        { en: 'season', zh: '季节', type: 'noun' , phonetic: '/ˈsiːzn/' },
        { en: 'spring', zh: '春天', type: 'noun' , phonetic: '/sprɪŋ/' },
        { en: 'summer', zh: '夏天', type: 'noun' , phonetic: '/ˈsʌmə/' },
        { en: 'autumn', zh: '秋天', type: 'noun' , phonetic: '/ˈɔːtəm/' },
        { en: 'winter', zh: '冬天', type: 'noun' , phonetic: '/ˈwɪntə/' },
        { en: 'change', zh: '变化', type: 'verb' },
        { en: 'leaf', zh: '叶子', type: 'noun' , phonetic: '/liːf/' },
        { en: 'tree', zh: '树', type: 'noun' , phonetic: '/triː/' },
        { en: 'flower', zh: '花', type: 'noun' , phonetic: '/ˈflaʊə/' },
        { en: 'snow', zh: '雪', type: 'noun' , phonetic: '/snəʊ/' },
        { en: 'ice', zh: '冰', type: 'noun' },
        { en: 'colourful', zh: '多彩的', type: 'adj' },
        { en: 'grow', zh: '生长', type: 'verb' },
        { en: 'fall', zh: '落下;秋天(美)', type: 'verb' },
        { en: 'which', zh: '哪一个', type: 'pron' },
        { en: 'because', zh: '因为', type: 'conj' },
        { en: 'love', zh: '爱;喜欢', type: 'verb' },
        { en: 'best', zh: '最好的;最', type: 'adv' , phonetic: '/best/' },
      ],
      phrases: [
        { en: 'fly a kite', zh: '放风筝' },
        { en: 'go swimming', zh: '去游泳' },
        { en: 'pick apples', zh: '摘苹果' },
        { en: 'make a snowman', zh: '堆雪人' },
        { en: 'green leaves', zh: '绿叶' },
        { en: 'colourful flowers', zh: '五颜六色的花' },
        { en: 'go on a picnic', zh: '去野餐' },
        { en: 'eat ice cream', zh: '吃冰淇淋' },
      ],
      sentences: [
        { en: "Whose sweater is this, Mum?", zh: "这是谁的毛衣，妈妈？" },
        { en: "It's your dad's.", zh: "是你爸爸的。" },
        { en: "Can I wear this new shirt today?", zh: "我今天可以穿这件新衬衫吗？" },
        { en: "Yes, but wear a coat too. It's cold and windy outside.", zh: "可以，但是再穿一件外套吧。外面有风，很冷。" },
        { en: "Which season do you like?", zh: "你喜欢哪个季节？" },
        { en: "Winter. It snows a lot.", zh: "冬天。冬天经常下雪。" },
        { en: "I like winter too. There are many festivals.", zh: "我也喜欢冬天。（在冬天）有很多节日。" },
        { en: "It's full of life.", zh: "（春天）充满生机。" },
        { en: "And enjoy mooncakes.", zh: "还品尝月饼。" },
        { en: "Then spring comes again.", zh: "接着春天又来了。" },
        { en: "Which season do you like best?", zh: "你最喜欢哪个季节？" },
        { en: "I like spring best.", zh: "我最喜欢春天。" },
        { en: "Why?", zh: "为什么？" },
        { en: "Because I can fly a kite.", zh: "因为我可以放风筝。" },
        { en: "Summer is hot. I can go swimming.", zh: "夏天很热。我可以去游泳。" },
        { en: "Autumn is golden and beautiful.", zh: "秋天是金色的，很美。" },
        { en: "I love winter. I can make a snowman.", zh: "我喜欢冬天。我可以堆雪人。" },
        { en: "Spring is warm. Flowers grow.", zh: "春天很温暖。花开了。" },
      ],
      grammar: [
        { title: 'Which ... do you like best?', content: '询问最喜欢哪个。Which season do you like best? = 你最喜欢哪个季节？' },
        { title: 'Why / Because', content: 'Why? = 为什么？Because ... = 因为……。用来问原因和答原因。' },
        { title: 'can + 动词原形', content: 'can 后面跟动词原形。I can fly a kite. = 我会放风筝。I can go swimming. = 我可以去游泳。' },
      ]
    }
  ],

  // ===================== 经典版教材 =====================
  old: [
    // Unit 1: My classroom
    {
      id: 'u1',
      title: 'Unit 1',
      subtitle: 'My classroom',
      titleCN: '我的教室',
      icon: '🏫',
      words: [
        { en: 'classroom', zh: '教室', type: 'noun' , phonetic: '/ˈklɑːsruːm/' },
        { en: 'window', zh: '窗户', type: 'noun' , phonetic: '/ˈwɪndəʊ/' },
        { en: 'blackboard', zh: '黑板', type: 'noun' , phonetic: '/ˈblækbɔːd/' },
        { en: 'light', zh: '电灯', type: 'noun' , phonetic: '/laɪt/' },
        { en: 'picture', zh: '图画', type: 'noun' , phonetic: '/ˈpɪktʃə/' },
        { en: 'door', zh: '门', type: 'noun' , phonetic: '/dɔː/' },
        { en: 'teacher\'s desk', zh: '讲台', type: 'noun' },
        { en: 'computer', zh: '计算机', type: 'noun' },
        { en: 'fan', zh: '风扇', type: 'noun' },
        { en: 'wall', zh: '墙壁', type: 'noun' , phonetic: '/wɔːl/' },
        { en: 'floor', zh: '地板', type: 'noun' , phonetic: '/flɔː/' },
        { en: 'really', zh: '真的', type: 'adv' },
        { en: 'near', zh: '距离近', type: 'prep' , phonetic: '/nɪə/' },
        { en: 'TV', zh: '电视', type: 'noun' },
        { en: 'clean', zh: '打扫;干净的', type: 'verb' , phonetic: '/kliːn/' },
        { en: 'help', zh: '帮助', type: 'verb' , phonetic: '/help/' },
      ],
      phrases: [
        { en: 'open the door', zh: '开门' },
        { en: 'turn on the light', zh: '开灯' },
        { en: 'close the window', zh: '关窗' },
        { en: 'clean the blackboard', zh: '擦黑板' },
        { en: 'put up the picture', zh: '挂图画' },
        { en: 'teacher\'s desk', zh: '讲台' },
      ],
      sentences: [
        { en: "We have a new classroom.", zh: "我们有一间新教室。" },
        { en: "Let's go and see!", zh: "我们去看看吧！" },
        { en: "Where is it?", zh: "它在哪里？" },
        { en: "It's near the window.", zh: "它在窗户旁边。" },
        { en: "Let's clean the classroom.", zh: "我们打扫教室吧。" },
        { en: "Let me clean the blackboard.", zh: "让我来擦黑板。" },
        { en: "What's in the classroom?", zh: "教室里有什么？" },
        { en: "One blackboard, one TV, many desks and chairs.", zh: "一块黑板、一台电视、许多桌椅。" },
      ],
      grammar: [
        { title: 'We have ...', content: '表示"我们有……"。We have a new classroom. = 我们有一间新教室。' },
        { title: 'Let\'s ... / Let me ...', content: 'Let\'s = 让我们……(提议一起做), Let me = 让我……(自己来做)。' },
        { title: '方位介词', content: 'near = 在……附近, in = 在……里面, on = 在……上面。Where is it? It\'s near the window.' },
      ]
    },
    // Unit 2: My schoolbag
    {
      id: 'u2',
      title: 'Unit 2',
      subtitle: 'My schoolbag',
      titleCN: '我的书包',
      icon: '🎒',
      words: [
        { en: 'schoolbag', zh: '书包', type: 'noun' , phonetic: '/ˈskuːlbæɡ/' },
        { en: 'maths book', zh: '数学书', type: 'noun' },
        { en: 'English book', zh: '英语书', type: 'noun' },
        { en: 'Chinese book', zh: '语文书', type: 'noun' },
        { en: 'storybook', zh: '故事书', type: 'noun' , phonetic: '/ˈstɔːribʊk/' },
        { en: 'candy', zh: '糖果', type: 'noun' , phonetic: '/ˈkændi/' },
        { en: 'notebook', zh: '笔记本', type: 'noun' , phonetic: '/ˈnəʊtbʊk/' },
        { en: 'toy', zh: '玩具', type: 'noun' , phonetic: '/tɔɪ/' },
        { en: 'key', zh: '钥匙', type: 'noun' , phonetic: '/kiː/' },
        { en: 'wow', zh: '哇', type: 'interj' },
        { en: 'lost', zh: '丢失', type: 'adj' , phonetic: '/lɒst/' },
        { en: 'so much', zh: '非常地', type: 'adv' },
        { en: 'cute', zh: '可爱的', type: 'adj' },
      ],
      phrases: [
        { en: 'put away', zh: '收起来' },
        { en: 'take out', zh: '拿出来' },
        { en: 'so much', zh: '非常地' },
        { en: 'a new schoolbag', zh: '一个新书包' },
        { en: 'in your schoolbag', zh: '在你的书包里' },
      ],
      sentences: [
        { en: "I have a new schoolbag.", zh: "我有一个新书包。" },
        { en: "What's in your schoolbag?", zh: "你书包里有什么？" },
        { en: "An English book, a maths book and three storybooks.", zh: "一本英语书、一本数学书和三本故事书。" },
        { en: "What colour is it?", zh: "它是什么颜色的？" },
        { en: "It's black and white.", zh: "它是黑白相间的。" },
        { en: "I lost my schoolbag.", zh: "我丢了我的书包。" },
        { en: "Here it is!", zh: "它在这里！" },
        { en: "Thank you so much!", zh: "非常感谢你！" },
      ],
      grammar: [
        { title: 'What\'s in ...?', content: '询问某物里面有什么。What\'s in your schoolbag? = 你书包里有什么？' },
        { title: 'What colour is ...?', content: '询问颜色。回答用 It\'s + 颜色。It\'s black and white. = 黑白相间。' },
        { title: '数字+名词复数', content: 'three storybooks, two notebooks。注意名词要用复数形式。' },
      ]
    },
    // Unit 3: My friends
    {
      id: 'u3',
      title: 'Unit 3',
      subtitle: 'My friends',
      titleCN: '我的朋友',
      icon: '👫',
      words: [
        { en: 'strong', zh: '强壮的', type: 'adj' , phonetic: '/strɒŋ/' },
        { en: 'friendly', zh: '友好的', type: 'adj' , phonetic: '/ˈfrendli/' },
        { en: 'quiet', zh: '安静的', type: 'adj' , phonetic: '/ˈkwaɪət/' },
        { en: 'hair', zh: '头发', type: 'noun' , phonetic: '/heə/' },
        { en: 'shoe', zh: '鞋', type: 'noun' , phonetic: '/ʃuː/' },
        { en: 'glasses', zh: '眼镜', type: 'noun' , phonetic: '/ˈɡlɑːsɪz/' },
        { en: 'his', zh: '他的', type: 'pron' , phonetic: '/hɪz/' },
        { en: 'her', zh: '她的', type: 'pron' , phonetic: '/hɜː/' },
        { en: 'or', zh: '或者', type: 'conj' },
        { en: 'right', zh: '正确的;右边', type: 'adj' , phonetic: '/raɪt/' },
        { en: 'hat', zh: '帽子', type: 'noun' },
      ],
      phrases: [
        { en: 'long hair', zh: '长头发' },
        { en: 'short hair', zh: '短头发' },
        { en: 'brown shoes', zh: '棕色的鞋子' },
        { en: 'blue glasses', zh: '蓝色的眼镜' },
        { en: 'tall and strong', zh: '又高又壮' },
        { en: 'a green bag', zh: '一个绿色的包' },
      ],
      sentences: [
        { en: "I have a new friend.", zh: "我有一个新朋友。" },
        { en: "What's his name?", zh: "他叫什么名字？" },
        { en: "His name is Zhang Peng.", zh: "他叫张鹏。" },
        { en: "He is tall and strong.", zh: "他又高又壮。" },
        { en: "She has long hair.", zh: "她有长头发。" },
        { en: "Who is he?", zh: "他是谁？" },
        { en: "He has glasses and his shoes are blue.", zh: "他戴着眼镜，他的鞋是蓝色的。" },
        { en: "You're right!", zh: "你说对了！" },
      ],
      grammar: [
        { title: 'He/She has ...', content: '第三人称单数用 has。He has glasses. She has long hair.' },
        { title: '形容词描述人', content: 'tall(高), short(矮), strong(壮), thin(瘦), friendly(友好), quiet(安静)' },
        { title: 'his vs her', content: 'his(他的)用于男生, her(她的)用于女生。' },
      ]
    },
    // Unit 4: My home
    {
      id: 'u4',
      title: 'Unit 4',
      subtitle: 'My home',
      titleCN: '我的家',
      icon: '🏠',
      words: [
        { en: 'bedroom', zh: '卧室', type: 'noun' , phonetic: '/ˈbedruːm/' },
        { en: 'living room', zh: '客厅', type: 'noun' , phonetic: '/ˈlɪvɪŋ ruːm/' },
        { en: 'study', zh: '书房', type: 'noun' , phonetic: '/ˈstʌdi/' },
        { en: 'kitchen', zh: '厨房', type: 'noun' , phonetic: '/ˈkɪtʃɪn/' },
        { en: 'bathroom', zh: '浴室', type: 'noun' , phonetic: '/ˈbɑːθruːm/' },
        { en: 'bed', zh: '床', type: 'noun' , phonetic: '/bed/' },
        { en: 'phone', zh: '电话', type: 'noun' , phonetic: '/fəʊn/' },
        { en: 'table', zh: '桌子', type: 'noun' , phonetic: '/ˈteɪbl/' },
        { en: 'sofa', zh: '沙发', type: 'noun' , phonetic: '/ˈsəʊfə/' },
        { en: 'fridge', zh: '冰箱', type: 'noun' , phonetic: '/frɪdʒ/' },
        { en: 'find', zh: '找到', type: 'verb' , phonetic: '/faɪnd/' },
        { en: 'them', zh: '他/她/它们', type: 'pron' },
      ],
      phrases: [
        { en: 'in the bedroom', zh: '在卧室里' },
        { en: 'in the living room', zh: '在客厅里' },
        { en: 'in the study', zh: '在书房里' },
        { en: 'in the kitchen', zh: '在厨房里' },
        { en: 'in the bathroom', zh: '在浴室里' },
        { en: 'on the table', zh: '在桌子上' },
        { en: 'near the phone', zh: '在电话旁边' },
      ],
      sentences: [
        { en: "Is she in the living room?", zh: "她在客厅吗？" },
        { en: "No, she isn't.", zh: "不，她不在。" },
        { en: "Where is she?", zh: "她在哪里？" },
        { en: "She is in the kitchen.", zh: "她在厨房。" },
        { en: "Where are the keys?", zh: "钥匙在哪里？" },
        { en: "Are they on the table?", zh: "它们在桌子上吗？" },
        { en: "Yes, they are.", zh: "是的。" },
        { en: "Open the door, please.", zh: "请开门。" },
      ],
      grammar: [
        { title: 'Is she/he in ...?', content: '询问某人在某地吗。Is she in the living room? 回答 Yes, she is. / No, she isn\'t.' },
        { title: 'Where is ...? / Where are ...?', content: 'Where is + 单数, Where are + 复数。Where are the keys?' },
        { title: '介词 in/on/near', content: 'in = 在……里面, on = 在……上面, near = 在……附近。' },
      ]
    },
    // Unit 5: Dinner's ready
    {
      id: 'u5',
      title: 'Unit 5',
      subtitle: "Dinner's ready",
      titleCN: '晚餐准备好了',
      icon: '🍽️',
      words: [
        { en: 'beef', zh: '牛肉', type: 'noun' , phonetic: '/biːf/' },
        { en: 'chicken', zh: '鸡肉', type: 'noun' , phonetic: '/ˈtʃɪkɪn/' },
        { en: 'noodles', zh: '面条', type: 'noun' , phonetic: '/ˈnuːdlz/' },
        { en: 'soup', zh: '汤', type: 'noun' , phonetic: '/suːp/' },
        { en: 'vegetable', zh: '蔬菜', type: 'noun' , phonetic: '/ˈvedʒtəbl/' },
        { en: 'chopsticks', zh: '筷子', type: 'noun' , phonetic: '/ˈtʃɒpstɪks/' },
        { en: 'bowl', zh: '碗', type: 'noun' , phonetic: '/bəʊl/' },
        { en: 'fork', zh: '叉子', type: 'noun' , phonetic: '/fɔːk/' },
        { en: 'knife', zh: '刀', type: 'noun' , phonetic: '/naɪf/' },
        { en: 'spoon', zh: '勺子', type: 'noun' , phonetic: '/spuːn/' },
        { en: 'dinner', zh: '晚餐', type: 'noun' , phonetic: '/ˈdɪnə/' },
        { en: 'ready', zh: '准备好了', type: 'adj' , phonetic: '/ˈredi/' },
        { en: 'pass', zh: '递给', type: 'verb' , phonetic: '/pɑːs/' },
        { en: 'try', zh: '尝试', type: 'verb' , phonetic: '/traɪ/' },
        { en: 'hungry', zh: '饿的', type: 'adj' , phonetic: '/ˈhʌŋɡri/' },
      ],
      phrases: [
        { en: 'some beef', zh: '一些牛肉' },
        { en: 'some vegetables', zh: '一些蔬菜' },
        { en: 'use chopsticks', zh: '用筷子' },
        { en: 'a knife and fork', zh: '一副刀叉' },
        { en: 'pass me the bowl', zh: '把碗递给我' },
        { en: 'help yourself', zh: '随便吃' },
      ],
      sentences: [
        { en: "What would you like?", zh: "你想要什么？" },
        { en: "I'd like some beef, please.", zh: "我想要一些牛肉。" },
        { en: "Would you like a knife and fork?", zh: "你想要刀叉吗？" },
        { en: "No, thanks. I can use chopsticks.", zh: "不了，谢谢。我会用筷子。" },
        { en: "Dinner's ready! Help yourself.", zh: "晚餐好了！随便吃。" },
        { en: "Pass me the bowl, please.", zh: "请把碗递给我。" },
        { en: "Can I have some noodles?", zh: "我可以吃些面条吗？" },
        { en: "Sure, here you are.", zh: "当然，给你。" },
      ],
      grammar: [
        { title: 'What would you like?', content: '询问对方想要什么。回答 I\'d like ... (= I would like ...)。' },
        { title: 'Would you like ...?', content: '礼貌地询问对方是否想要……。回答 Yes, please. / No, thanks.' },
        { title: 'Can I have ...?', content: '礼貌地请求某物。Can I have some noodles? = 我可以吃些面条吗？' },
      ]
    },
    // Unit 6: Meet my family!
    {
      id: 'u6',
      title: 'Unit 6',
      subtitle: 'Meet my family!',
      titleCN: '见见我的家人',
      icon: '👨‍👩‍👧‍👦',
      words: [
        { en: 'parents', zh: '父母', type: 'noun' , phonetic: '/ˈpeərənts/' },
        { en: 'cousin', zh: '表(堂)兄弟姐妹', type: 'noun' , phonetic: '/ˈkʌzn/' },
        { en: 'uncle', zh: '叔叔;舅舅', type: 'noun' , phonetic: '/ˈʌŋkl/' },
        { en: 'aunt', zh: '阿姨;姑姑', type: 'noun' , phonetic: '/ɑːnt/' },
        { en: 'baby brother', zh: '婴儿小弟弟', type: 'noun' },
        { en: 'doctor', zh: '医生', type: 'noun' , phonetic: '/ˈdɒktə/' },
        { en: 'cook', zh: '厨师', type: 'noun' , phonetic: '/kʊk/' },
        { en: 'driver', zh: '司机', type: 'noun' , phonetic: '/ˈdraɪvə/' },
        { en: 'farmer', zh: '农民', type: 'noun' , phonetic: '/ˈfɑːmə/' },
        { en: 'nurse', zh: '护士', type: 'noun' , phonetic: '/nɜːs/' },
        { en: 'people', zh: '人们', type: 'noun' , phonetic: '/ˈpiːpl/' },
        { en: 'but', zh: '但是', type: 'conj' },
        { en: 'little', zh: '小的', type: 'adj' },
        { en: 'puppy', zh: '小狗', type: 'noun' },
        { en: 'football player', zh: '足球运动员', type: 'noun' },
        { en: 'job', zh: '工作', type: 'noun' , phonetic: '/dʒɒb/' },
        { en: 'basketball', zh: '篮球', type: 'noun' },
      ],
      phrases: [
        { en: 'how many', zh: '多少' },
        { en: 'my parents', zh: '我的父母' },
        { en: 'baby brother', zh: '婴儿小弟弟' },
        { en: 'football player', zh: '足球运动员' },
        { en: 'on the tree', zh: '在树上' },
      ],
      sentences: [
        { en: "How many people are there in your family?", zh: "你家有几口人？" },
        { en: "My family has six people.", zh: "我家有六口人。" },
        { en: "Who are they?", zh: "他们是谁？" },
        { en: "My parents, my uncle, my aunt, my cousin and me.", zh: "我的父母、叔叔、阿姨、表弟和我。" },
        { en: "Is this your uncle?", zh: "这是你叔叔吗？" },
        { en: "Yes, it is. He's a football player.", zh: "是的。他是一名足球运动员。" },
        { en: "What's your aunt's job?", zh: "你阿姨的工作是什么？" },
        { en: "She's a nurse.", zh: "她是一名护士。" },
      ],
      grammar: [
        { title: 'How many ... are there?', content: '询问数量。How many people are there in your family? = 你家有几口人？' },
        { title: 'What\'s ... job?', content: '询问某人的工作。What\'s your aunt\'s job? = 你阿姨的工作是什么？' },
        { title: '名词所有格', content: 'aunt\'s job = 阿姨的工作, father\'s = 爸爸的。用 \'s 表示所属关系。' },
      ]
    }
  ]
};
